document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/catalog.css?v=24"><link rel="stylesheet" href="/orders.css?v=24">');
const catalog=[
['Guaracamp 285 ml','Bebidas',2],['Coca-Cola 200 ml','Bebidas',3.5],['Fanta Laranja 200 ml','Bebidas',3.5],['Fanta Guaraná 200 ml','Bebidas',3.5],['Energético 300 ml','Bebidas',8],['Suco de Manga 300 ml','Bebidas',6],['Suco de Goiaba 300 ml','Bebidas',6],
['Torta Salgada Pequena','Tortas salgadas',7],['Torta Salgada Grande','Tortas salgadas',13],['Empadão de Frango','Tortas salgadas',7],['Empadão de Camarão','Tortas salgadas',8],['Queijo com Presunto','Fritos',6],['Quibe','Fritos',6],['Risolho','Fritos',6],['Coxinha','Fritos',6],
['Joelho Calabresa','Assados',7],['Joelho Queijo com Presunto','Assados',7],['Joelho Frango','Assados',7],['Joelho Salsicha','Assados',7],['Croissant Queijo','Assados',7],['Croissant Queijo com Presunto','Assados',7],['Hambúrguer com Cheddar','Assados',7],['Hambúrguer com Queijo e Presunto','Assados',7],['Pastel de Forno','Assados',7],
['Torta de Limão','Sobremesas',10],['Torta de Chocolate','Sobremesas',10],['Torta de Maracujá','Sobremesas',10],['Pavê de Paçoca','Sobremesas',10],['Pavê de Chocolate','Sobremesas',10],['Pavê de Limão','Sobremesas',10],['Bolo de Chocolate com Amendoim','Sobremesas',10],['Bolo de Prestígio','Sobremesas',10],['Bolo de Cenoura com Chocolate','Sobremesas',10],['Bolo de Chocolate com Limão','Sobremesas',10],['Bolo de Doce de Leite com Ameixa','Sobremesas',10]
];
const imageIndex=new Map(catalog.map((p,i)=>[p[0].toLocaleLowerCase('pt-BR'),i]));
const specialImages={
'guaracamp 285 ml':'/assets/guaracamp-v2.webp','coca-cola 200 ml':'/assets/coca-cola.webp','fanta laranja 200 ml':'/assets/fanta-laranja.webp','fanta guaraná 200 ml':'/assets/fanta-guarana.webp','energético 300 ml':'/assets/energetico-baly-v2.webp','suco de manga 300 ml':'/assets/suco-manga-v4.webp','suco de goiaba 300 ml':'/assets/suco-goiaba-v4.webp','torta salgada pequena':'/assets/torta-salgada-v21.png','torta salgada grande':'/assets/torta-salgada-v21.png','queijo com presunto':'/assets/queijo-presunto-frito.webp',
'joelho calabresa':'/assets/assado-joelho-calabresa-v20.png','joelho queijo com presunto':'/assets/assado-joelho-queijo-presunto-v20.png','joelho frango':'/assets/assado-joelho-frango-v20.png','joelho salsicha':'/assets/assado-joelho-salsicha-v20.png','croissant queijo':'/assets/assado-croissant-queijo-v20.png','croissant queijo com presunto':'/assets/assado-croissant-queijo-presunto-v20.png','hambúrguer com cheddar':'/assets/assado-hamburguer-cheddar-v20.png','hambúrguer com queijo e presunto':'/assets/assado-hamburguer-queijo-presunto-v20.png','pastel de forno':'/assets/assado-pastel-forno-v20.png','torta de maracujá':'/assets/torta-maracuja-v20.png'
};
const treatedImageNumbers=new Set([10,11,12,13,14,15,24,25,26,28,29,30,31,32,33,34,35]);
const fallbackDescriptions={
'Guaracamp 285 ml':'Bebida Guaracamp • 285 ml.','Coca-Cola 200 ml':'Refrigerante Coca-Cola • 200 ml.','Fanta Laranja 200 ml':'Refrigerante sabor laranja • 200 ml.','Fanta Guaraná 200 ml':'Refrigerante sabor guaraná • 200 ml.','Energético 300 ml':'Bebida energética • 300 ml.','Suco de Manga 300 ml':'Suco sabor manga • 300 ml.','Suco de Goiaba 300 ml':'Suco sabor goiaba • 300 ml.','Torta Salgada Pequena':'Torta salgada • tamanho pequeno.','Torta Salgada Grande':'Torta salgada • tamanho grande.','Empadão de Frango':'Empadão salgado com recheio de frango.','Empadão de Camarão':'Empadão salgado com recheio de camarão.','Queijo com Presunto':'Salgado frito de queijo com presunto.','Quibe':'Salgado frito • quibe.','Risolho':'Salgado frito • risolho.','Coxinha':'Salgado frito • coxinha.','Joelho Calabresa':'Salgado assado • sabor calabresa.','Joelho Queijo com Presunto':'Salgado assado de queijo com presunto.','Joelho Frango':'Salgado assado • sabor frango.','Joelho Salsicha':'Salgado assado • sabor salsicha.','Croissant Queijo':'Croissant assado • sabor queijo.','Croissant Queijo com Presunto':'Croissant assado de queijo com presunto.','Hambúrguer com Cheddar':'Salgado assado de hambúrguer com cheddar.','Hambúrguer com Queijo e Presunto':'Salgado assado de hambúrguer, queijo e presunto.','Pastel de Forno':'Pastel assado no forno.','Torta de Limão':'Sobremesa sabor limão.','Torta de Chocolate':'Sobremesa sabor chocolate.','Torta de Maracujá':'Sobremesa sabor maracujá.','Pavê de Paçoca':'Sobremesa • pavê sabor paçoca.','Pavê de Chocolate':'Sobremesa • pavê sabor chocolate.','Pavê de Limão':'Sobremesa • pavê sabor limão.','Bolo de Chocolate com Amendoim':'Bolo de chocolate com amendoim.','Bolo de Prestígio':'Bolo sabor prestígio.','Bolo de Cenoura com Chocolate':'Bolo de cenoura com chocolate.','Bolo de Chocolate com Limão':'Bolo de chocolate com limão.','Bolo de Doce de Leite com Ameixa':'Bolo de doce de leite com ameixa.'};
const fallbackFeatured=['Torta Salgada Pequena','Torta Salgada Grande','Empadão de Frango','Joelho Queijo com Presunto','Queijo com Presunto','Torta de Limão'];
const categoryOrder=['Tortas salgadas','Assados','Fritos','Sobremesas','Bebidas'];
const fallback=catalog.map((p,i)=>({id:i+1,name:p[0],category:p[1],price:p[2],available:1,stock:null,description:fallbackDescriptions[p[0]]||'',featured:fallbackFeatured.includes(p[0])?1:0,featured_order:fallbackFeatured.indexOf(p[0])+1}));
const $=s=>document.querySelector(s),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));let products=[],cart=new Map(),category='Todos';
async function load(){try{const r=await fetch('/api/products');if(!r.ok)throw 0;products=await r.json()}catch{products=products.length?products.map(p=>({...p,available:0})):fallback.map(p=>({...p,available:0}));toast("Sem conexão com o estoque. Atualize para verificar a disponibilidade.")}products.sort((a,b)=>(categoryOrder.indexOf(a.category)-categoryOrder.indexOf(b.category))||Number(a.id)-Number(b.id));renderFilters();renderFeatured();renderProducts();renderCart()}
function renderFilters(){const present=new Set(products.map(p=>p.category)),values=['Todos',...categoryOrder.filter(value=>present.has(value))];$('#filters').innerHTML=values.map(v=>`<button class="filter ${v===category?'active':''}" data-filter="${v}">${v}</button>`).join('')}
function pictureStyle(name){const i=imageIndex.get(name.toLocaleLowerCase('pt-BR'))??0,row=Math.floor(i/7),col=i%7;return `--photo-x:${col};--photo-y:${row}`}
function productPicture(name){const key=name.toLocaleLowerCase('pt-BR'),i=imageIndex.get(key)??0,number=i+1,suffix=treatedImageNumbers.has(number)?'-v2':'',src=specialImages[key]||`/assets/produto-${String(number).padStart(2,'0')}${suffix}.webp`;return `<div class="product-photo product-photo-file"><img src="${src}" alt="${name}" loading="lazy"></div>`}
function productCard(p,featured=false){const stock=p.stock===null?'':Number(p.stock)<=Number(p.low_stock_threshold??5)?`<small class="stock-warning">Últimas ${p.stock} unidade(s)</small>`:'';return `<article class="card ${featured?'featured-card':''} ${p.available?'':'off'}">${productPicture(p.name)}<div class="card-body">${featured?'<span class="featured-badge">Destaque</span>':''}<div class="card-top"><h3>${escapeHtml(p.name)}</h3><span class="status">${p.available?'Disponível':'Esgotado'}</span></div><p class="product-description">${escapeHtml(p.description||'')}</p>${p.available?stock:''}<p class="price">${money(p.price)}</p><button class="add" data-add="${p.id}" ${p.available?'':'disabled'}>${p.available?'Adicionar':'Produto esgotado'}</button></div></article>`}
function renderFeatured(){const values=products.filter(p=>Number(p.featured)).sort((a,b)=>Number(a.featured_order||99)-Number(b.featured_order||99)).slice(0,6),section=$('#featured-section');section.hidden=!values.length;$('#featured-grid').innerHTML=values.map(p=>productCard(p,true)).join('')}
function renderProducts(){const values=category==='Todos'?products:products.filter(p=>p.category===category);$('#product-grid').innerHTML=values.map(p=>productCard(p)).join('')}
function renderCart(){let total=0,count=0;$('#cart-items').innerHTML=[...cart].map(([id,q])=>{const p=products.find(x=>+x.id===id);if(!p)return'';total+=p.price*q;count+=q;return `<div class="cart-item"><div><strong>${p.name}</strong><p>${money(p.price)} cada</p></div><div class="qty"><button data-id="${id}" data-d="-1">−</button><b>${q}</b><button data-id="${id}" data-d="1">+</button></div></div>`}).join('');$('#empty').hidden=cart.size>0;$('#cart-count').textContent=count;$('#cart-total').textContent=money(total);document.dispatchEvent(new Event('lg-cart-changed'))}
function add(id){if(window.LGOrders&&!LGOrders.canChangeCart())return;window.LGOrders?.beforeAdd();const p=products.find(x=>+x.id===id);if(!p?.available)return;const next=(cart.get(id)||0)+1;if(p.stock!==null&&next>Number(p.stock))return toast(`Só restam ${p.stock} unidade(s) de ${p.name}`);cart.set(id,next);renderCart();toast(`${p.name} adicionado`)}function qty(id,d){if(window.LGOrders&&!LGOrders.canChangeCart())return;const p=products.find(x=>+x.id===id),q=(cart.get(id)||0)+d;if(p?.stock!==null&&q>Number(p.stock))return toast(`Estoque máximo: ${p.stock}`);q<1?cart.delete(id):cart.set(id,q);renderCart()}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}function open(){ $('#drawer').scrollTop=0;$('#drawer').removeAttribute('inert');$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#backdrop').hidden=false}function close(){ $('#drawer').setAttribute('inert','');$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');$('#backdrop').hidden=true}
$('#filters').onclick=e=>{if(e.target.dataset.filter){category=e.target.dataset.filter;renderFilters();renderProducts()}};for(const id of ['product-grid','featured-grid'])$('#'+id).onclick=e=>e.target.dataset.add&&add(+e.target.dataset.add);$('#cart-items').onclick=e=>e.target.dataset.id&&qty(+e.target.dataset.id,+e.target.dataset.d);$('#open-cart').onclick=open;$('#close-cart').onclick=close;$('#backdrop').onclick=close;
// The customer module owns checkout and durable order access.
load();
