document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/catalog.css">');
const catalog=[
['Guaracamp 285 ml','Bebidas',2],['Coca-Cola 200 ml','Bebidas',3.5],['Fanta Laranja 200 ml','Bebidas',3.5],['Fanta Guaraná 200 ml','Bebidas',3.5],['Energético 300 ml','Bebidas',8],['Suco de Manga 300 ml','Bebidas',6],['Suco de Goiaba 300 ml','Bebidas',6],
['Torta Salgada Pequena','Tortas salgadas',7],['Torta Salgada Grande','Tortas salgadas',13],['Empadão de Frango','Tortas salgadas',7],['Empadão de Camarão','Tortas salgadas',8],['Queijo com Presunto','Fritos',6],['Quibe','Fritos',6],['Risolho','Fritos',6],['Coxinha','Fritos',6],
['Joelho Calabresa','Assados',7],['Joelho Queijo com Presunto','Assados',7],['Joelho Frango','Assados',7],['Joelho Salsicha','Assados',7],['Croissant Queijo','Assados',7],['Croissant Queijo com Presunto','Assados',7],['Hambúrguer com Cheddar','Assados',7],['Hambúrguer com Queijo e Presunto','Assados',7],['Pastel de Forno','Assados',7],
['Torta de Limão','Sobremesas',10],['Torta de Chocolate','Sobremesas',10],['Torta de Maracujá','Sobremesas',10],['Pavê de Paçoca','Sobremesas',10],['Pavê de Chocolate','Sobremesas',10],['Pavê de Limão','Sobremesas',10],['Bolo de Chocolate com Amendoim','Sobremesas',10],['Bolo de Prestígio','Sobremesas',10],['Bolo de Cenoura com Chocolate','Sobremesas',10],['Bolo de Chocolate com Limão','Sobremesas',10],['Bolo de Doce de Leite com Ameixa','Sobremesas',10]
];
const imageIndex=new Map(catalog.map((p,i)=>[p[0].toLocaleLowerCase('pt-BR'),i]));
const fallback=catalog.map((p,i)=>({id:i+1,name:p[0],category:p[1],price:p[2],available:1}));
const $=s=>document.querySelector(s),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let products=[],cart=new Map(),category='Todos';
async function load(){try{const r=await fetch('/api/products');if(!r.ok)throw 0;products=await r.json()}catch{products=fallback}renderFilters();renderProducts();renderCart()}
function renderFilters(){const values=['Todos',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=values.map(v=>`<button class="filter ${v===category?'active':''}" data-filter="${v}">${v}</button>`).join('')}
function pictureStyle(name){const i=imageIndex.get(name.toLocaleLowerCase('pt-BR'))??0,row=Math.floor(i/7),col=i%7;return `--photo-x:${col};--photo-y:${row}`}
function renderProducts(){const values=category==='Todos'?products:products.filter(p=>p.category===category);$('#product-grid').innerHTML=values.map(p=>`<article class="card ${p.available?'':'off'}"><div class="product-photo" role="img" aria-label="${p.name}" style="${pictureStyle(p.name)}"></div><div class="card-body"><div class="card-top"><div><h3>${p.name}</h3><p class="category">${p.category}</p></div><span class="status">${p.available?'Disponível':'Esgotado'}</span></div><p class="price">${money(p.price)}</p><button class="add" data-add="${p.id}" ${p.available?'':'disabled'}>${p.available?'Adicionar':'Indisponível hoje'}</button></div></article>`).join('')}
function renderCart(){let total=0,count=0;$('#cart-items').innerHTML=[...cart].map(([id,q])=>{const p=products.find(x=>+x.id===id);if(!p)return'';total+=p.price*q;count+=q;return `<div class="cart-item"><div><strong>${p.name}</strong><p>${money(p.price)} cada</p></div><div class="qty"><button data-id="${id}" data-d="-1">−</button><b>${q}</b><button data-id="${id}" data-d="1">+</button></div></div>`}).join('');$('#empty').hidden=cart.size>0;$('#cart-count').textContent=count;$('#cart-total').textContent=money(total)}
function add(id){const p=products.find(x=>+x.id===id);if(!p?.available)return;cart.set(id,(cart.get(id)||0)+1);renderCart();toast(`${p.name} adicionado`)}function qty(id,d){const q=(cart.get(id)||0)+d;q<1?cart.delete(id):cart.set(id,q);renderCart()}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1700)}function open(){ $('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#backdrop').hidden=false}function close(){ $('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');$('#backdrop').hidden=true}
$('#filters').onclick=e=>{if(e.target.dataset.filter){category=e.target.dataset.filter;renderFilters();renderProducts()}};$('#product-grid').onclick=e=>e.target.dataset.add&&add(+e.target.dataset.add);$('#cart-items').onclick=e=>e.target.dataset.id&&qty(+e.target.dataset.id,+e.target.dataset.d);$('#open-cart').onclick=open;$('#close-cart').onclick=close;$('#backdrop').onclick=close;
$('#checkout').onsubmit=e=>{e.preventDefault();if(!cart.size)return toast('Adicione pelo menos um produto');const name=$('#customer-name').value.trim(),sector=$('#customer-sector').value.trim(),note=$('#customer-note').value.trim();let total=0;const lines=[...cart].map(([id,q])=>{const p=products.find(x=>+x.id===id);total+=p.price*q;return `• ${q}x ${p.name} — ${money(p.price*q)}`});const text=[`Olá, L&G Delícias! Gostaria de fazer um pedido.`,``,`*Cliente:* ${name}`,`*Setor:* ${sector}`,``,`*Itens:*`,...lines,``,`*Total:* ${money(total)}`,note?`*Observação:* ${note}`:'',``,`Pedido para retirada no local. Aguardo a confirmação.`].filter(Boolean).join('\n');window.open(`https://wa.me/5521989397049?text=${encodeURIComponent(text)}`,'_blank')};load();
