document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/catalog.css?v=16"><link rel="stylesheet" href="/orders.css?v=16">');
const catalog=[
['Guaracamp 285 ml','Bebidas',2],['Coca-Cola 200 ml','Bebidas',3.5],['Fanta Laranja 200 ml','Bebidas',3.5],['Fanta Guaraná 200 ml','Bebidas',3.5],['Energético 300 ml','Bebidas',8],['Suco de Manga 300 ml','Bebidas',6],['Suco de Goiaba 300 ml','Bebidas',6],
['Torta Salgada Pequena','Tortas salgadas',7],['Torta Salgada Grande','Tortas salgadas',13],['Empadão de Frango','Tortas salgadas',7],['Empadão de Camarão','Tortas salgadas',8],['Queijo com Presunto','Fritos',6],['Quibe','Fritos',6],['Risolho','Fritos',6],['Coxinha','Fritos',6],
['Joelho Calabresa','Assados',7],['Joelho Queijo com Presunto','Assados',7],['Joelho Frango','Assados',7],['Joelho Salsicha','Assados',7],['Croissant Queijo','Assados',7],['Croissant Queijo com Presunto','Assados',7],['Hambúrguer com Cheddar','Assados',7],['Hambúrguer com Queijo e Presunto','Assados',7],['Pastel de Forno','Assados',7],
['Torta de Limão','Sobremesas',10],['Torta de Chocolate','Sobremesas',10],['Torta de Maracujá','Sobremesas',10],['Pavê de Paçoca','Sobremesas',10],['Pavê de Chocolate','Sobremesas',10],['Pavê de Limão','Sobremesas',10],['Bolo de Chocolate com Amendoim','Sobremesas',10],['Bolo de Prestígio','Sobremesas',10],['Bolo de Cenoura com Chocolate','Sobremesas',10],['Bolo de Chocolate com Limão','Sobremesas',10],['Bolo de Doce de Leite com Ameixa','Sobremesas',10]
];
const imageIndex=new Map(catalog.map((p,i)=>[p[0].toLocaleLowerCase('pt-BR'),i]));
const specialImages={
'guaracamp 285 ml':'/assets/guaracamp-v2.webp','coca-cola 200 ml':'/assets/coca-cola.webp','fanta laranja 200 ml':'/assets/fanta-laranja.webp','fanta guaraná 200 ml':'/assets/fanta-guarana.webp','energético 300 ml':'/assets/energetico-baly-v2.webp','suco de manga 300 ml':'/assets/suco-manga-v4.webp','suco de goiaba 300 ml':'/assets/suco-goiaba-v4.webp','torta salgada pequena':'/assets/torta-salgada.webp','torta salgada grande':'/assets/torta-salgada.webp','queijo com presunto':'/assets/queijo-presunto-frito.webp',
'joelho calabresa':'/assets/assado-joelho-calabresa-v20.png','joelho queijo com presunto':'/assets/assado-joelho-queijo-presunto-v20.png','joelho frango':'/assets/assado-joelho-frango-v20.png','joelho salsicha':'/assets/assado-joelho-salsicha-v20.png','croissant queijo':'/assets/assado-croissant-queijo-v20.png','croissant queijo com presunto':'/assets/assado-croissant-queijo-presunto-v20.png','hambúrguer com cheddar':'/assets/assado-hamburguer-cheddar-v20.png','hambúrguer com queijo e presunto':'/assets/assado-hamburguer-queijo-presunto-v20.png','pastel de forno':'/assets/assado-pastel-forno-v20.png','torta de maracujá':'/assets/torta-maracuja-v20.png'
};
const treatedImageNumbers=new Set([10,11,12,13,14,15,24,25,26,28,29,30,31,32,33,34,35]);
const fallback=catalog.map((p,i)=>({id:i+1,name:p[0],category:p[1],price:p[2],available:1}));
const $=s=>document.querySelector(s),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let products=[],cart=new Map(),category='Todos';
async function load(){try{const r=await fetch('/api/products');if(!r.ok)throw 0;products=await r.json()}catch{products=fallback}renderFilters();renderProducts();renderCart()}
function renderFilters(){const values=['Todos',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=values.map(v=>`<button class="filter ${v===category?'active':''}" data-filter="${v}">${v}</button>`).join('')}
function pictureStyle(name){const i=imageIndex.get(name.toLocaleLowerCase('pt-BR'))??0,row=Math.floor(i/7),col=i%7;return `--photo-x:${col};--photo-y:${row}`}
function productPicture(name){const key=name.toLocaleLowerCase('pt-BR'),i=imageIndex.get(key)??0,number=i+1,suffix=treatedImageNumbers.has(number)?'-v2':'',src=specialImages[key]||`/assets/produto-${String(number).padStart(2,'0')}${suffix}.webp`;return `<div class="product-photo product-photo-file"><img src="${src}" alt="${name}" loading="lazy"></div>`}
function renderProducts(){const values=category==='Todos'?products:products.filter(p=>p.category===category);$('#product-grid').innerHTML=values.map(p=>`<article class="card ${p.available?'':'off'}">${productPicture(p.name)}<div class="card-body"><div class="card-top"><div><h3>${p.name}</h3><p class="category">${p.category}</p></div><span class="status">${p.available?'Disponível':'Esgotado'}</span></div><p class="price">${money(p.price)}</p><button class="add" data-add="${p.id}" ${p.available?'':'disabled'}>${p.available?'Adicionar':'Indisponível hoje'}</button></div></article>`).join('')}
function renderCart(){let total=0,count=0;$('#cart-items').innerHTML=[...cart].map(([id,q])=>{const p=products.find(x=>+x.id===id);if(!p)return'';total+=p.price*q;count+=q;return `<div class="cart-item"><div><strong>${p.name}</strong><p>${money(p.price)} cada</p></div><div class="qty"><button data-id="${id}" data-d="-1">−</button><b>${q}</b><button data-id="${id}" data-d="1">+</button></div></div>`}).join('');$('#empty').hidden=cart.size>0;$('#cart-count').textContent=count;$('#cart-total').textContent=money(total)}
function add(id){const p=products.find(x=>+x.id===id);if(!p?.available)return;cart.set(id,(cart.get(id)||0)+1);renderCart();toast(`${p.name} adicionado`)}function qty(id,d){const q=(cart.get(id)||0)+d;q<1?cart.delete(id):cart.set(id,q);renderCart()}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1700)}function open(){ $('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#backdrop').hidden=false}function close(){ $('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');$('#backdrop').hidden=true}
$('#filters').onclick=e=>{if(e.target.dataset.filter){category=e.target.dataset.filter;renderFilters();renderProducts()}};$('#product-grid').onclick=e=>e.target.dataset.add&&add(+e.target.dataset.add);$('#cart-items').onclick=e=>e.target.dataset.id&&qty(+e.target.dataset.id,+e.target.dataset.d);$('#open-cart').onclick=open;$('#close-cart').onclick=close;$('#backdrop').onclick=close;
$('#checkout').onsubmit=async e=>{e.preventDefault();if(!cart.size)return toast('Adicione pelo menos um produto');const name=$('#customer-name').value.trim(),sector=$('#customer-sector').value.trim(),phone=$('#customer-phone').value.trim(),note=$('#customer-note').value.trim();if(!name||!sector)return toast('Preencha seu nome e setor');const button=$('#submit-order');button.disabled=true;button.textContent='Registrando pedido…';try{const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,sector,phone,note,items:[...cart].map(([productId,quantity])=>({productId,quantity}))})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível registrar o pedido.');cart.clear();renderCart();$('#checkout-area').hidden=true;$('#order-code').textContent=data.code;$('#order-success').hidden=false}catch(err){toast(err.message)}finally{button.disabled=false;button.textContent='Confirmar pedido'}};
$('#new-order').onclick=()=>{$('#order-success').hidden=true;$('#checkout-area').hidden=false;$('#checkout').reset();close()};load();
