import test from 'node:test';
import assert from 'node:assert/strict';
import {testDB} from './d1-test-db.mjs';
import * as admin from '../functions/api/orders.js';
import * as customer from '../functions/api/customer-order.js';
import {setup,secret} from '../server/order-core.js';

async function fixture(){
  const db=testDB(),env={DB:db.DB,ADMIN_KEY:'local-test-only'};await setup(env.DB);
  db.sqlite.exec("INSERT INTO products(id,name,category,price,available,stock) VALUES(1,'Guaracamp 285 ml','Bebidas',2,1,30),(2,'Torta Salgada Grande','Tortas salgadas',13,1,30)");
  const call=async(mod,method,url,body,headers={})=>{const request=new Request('http://localhost'+url,{method,headers:{'content-type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});const response=await mod['onRequest'+method[0]+method.slice(1).toLowerCase()]({request,env});return {status:response.status,...await response.json()}};
  const create=(token=secret(),items=[{productId:1,quantity:1},{productId:2,quantity:1}])=>call(admin,'POST','/api/orders',{name:'Cliente de teste',sector:'Teste',phone:'21900000000',paymentMethod:'later',items,accessToken:token});
  const patch=(o,body)=>call(admin,'PATCH','/api/orders?id='+o.id,body,{'x-admin-key':env.ADMIN_KEY});
  const get=token=>call(customer,'GET','/api/customer-order',null,{authorization:'Bearer '+token});
  const quote=(token,items=[{productId:2,quantity:1}],clientKey=crypto.randomUUID())=>call(customer,'POST','/api/customer-order?action=quote',{items,clientKey},{authorization:'Bearer '+token});
  const submit=(token,a)=>call(customer,'POST','/api/customer-order?action=submit',{additionId:a.id,expectedRevision:a.revision},{authorization:'Bearer '+token});
  const decide=(o,a,decision='approve',reason='')=>patch(o,{action:'addition',additionId:a.id,expectedRevision:a.revision,decision,reason});
  const stock=id=>db.sqlite.prepare('SELECT stock FROM products WHERE id=?').get(id).stock;
  return {...db,env,call,create,patch,get,quote,submit,decide,stock};
}
test('Guaracamp + torta: mantém código, soma quantidades e desconta apenas o adicional',async()=>{const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken),r=await f.submit(a.accessToken,q.addition);assert.equal(r.status,200);assert.equal(r.order.code,a.code);assert.equal(r.order.total,28);assert.deepEqual(r.order.items.map(i=>i.quantity),[1,2]);assert.equal(f.stock(1),29);assert.equal(f.stock(2),28);assert.equal(r.order.balance_cents,2800);assert.equal(r.order.events[0].actor,'Cliente');f.close()});
test('pedido pago preserva R$15 recebidos e lança apenas R$13 pendentes',async()=>{const f=await fixture(),a=await f.create();await f.patch(a.order,{paymentStatus:'paid'});const q=await f.quote(a.accessToken),r=await f.submit(a.accessToken,q.addition);assert.equal(r.order.paid_amount_cents,1500);assert.equal(r.order.balance_cents,1300);assert.equal(r.order.payment_status,'pending');const fin=await f.call(admin,'GET','/api/orders?finance=1',null,{'x-admin-key':f.env.ADMIN_KEY});assert.deepEqual([fin.summary.revenue,fin.summary.paid,fin.summary.pending],[28,15,13]);await f.patch(r.order,{paymentStatus:'paid'});assert.deepEqual(f.sqlite.prepare('SELECT amount_cents FROM order_payments ORDER BY rowid').all().map(i=>i.amount_cents),[1500,1300]);f.close()});
test('confirmado: solicita sem baixa/cobrança e aprova sem duplicar',async()=>{const f=await fixture(),a=await f.create();await f.patch(a.order,{status:'preparing'});const q=await f.quote(a.accessToken),s=await f.submit(a.accessToken,q.addition);assert.equal(s.addition.state,'pending');assert.equal(s.order.total,15);assert.equal(f.stock(2),29);const [r,r2]=await Promise.all([f.decide(s.order,s.addition),f.decide(s.order,s.addition)]);assert.equal(r.status,200);assert.equal(r2.status,200);assert.equal((await f.get(a.accessToken)).order.total,28);assert.equal(f.stock(2),28);f.close()});
test('recusa guarda motivo sem cobrar nem alterar estoque',async()=>{const f=await fixture(),a=await f.create();await f.patch(a.order,{status:'preparing'});const q=await f.quote(a.accessToken),s=await f.submit(a.accessToken,q.addition),r=await f.decide(s.order,s.addition,'reject','Produção encerrada');assert.equal(r.addition.state,'rejected');assert.equal(r.addition.reason,'Produção encerrada');assert.equal(r.order.total,15);assert.equal(f.stock(2),29);f.close()});
test('falta de estoque impede aprovação com motivo; solicitação permanece pendente',async()=>{const f=await fixture(),a=await f.create();await f.patch(a.order,{status:'preparing'});const q=await f.quote(a.accessToken),s=await f.submit(a.accessToken,q.addition);f.sqlite.exec('UPDATE products SET stock=0 WHERE id=2');const r=await f.decide(s.order,s.addition);assert.equal(r.code,'STOCK');assert.match(r.error,/Restam 0/);const actual=await f.get(a.accessToken);assert.equal(actual.order.total,15);assert.equal(actual.order.additions[0].state,'pending');f.close()});
test('clique duplo e reenvio: um pedido e um acréscimo',async()=>{const f=await fixture(),token=secret(),[a,b]=await Promise.all([f.create(token),f.create(token)]);assert.equal(a.code,b.code);assert.equal(f.stock(2),29);const key=crypto.randomUUID(),[q,q2]=await Promise.all([f.quote(token,undefined,key),f.quote(token,undefined,key)]);assert.equal(q.addition.id,q2.addition.id);const [r,r2]=await Promise.all([f.submit(token,q.addition),f.submit(token,q.addition)]);assert.equal(r.status,200);assert.equal(r2.status,200);assert.equal(f.stock(2),28);assert.equal((await f.get(token)).order.total,28);f.close()});
test('dois pedidos concorrentes disputam a última unidade',async()=>{const f=await fixture(),a=await f.create(),b=await f.create();f.sqlite.exec('UPDATE products SET stock=1 WHERE id=2');const q=await f.quote(a.accessToken),q2=await f.quote(b.accessToken);const results=await Promise.all([f.submit(a.accessToken,q.addition),f.submit(b.accessToken,q2.addition)]);assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(f.stock(2),0);assert.equal(f.sqlite.prepare('SELECT SUM(total) n FROM orders').get().n,43);f.close()});
test('novo pedido concorrente com acréscimo não vende a última unidade duas vezes',async()=>{const f=await fixture(),a=await f.create();f.sqlite.exec('UPDATE products SET stock=1 WHERE id=2');const q=await f.quote(a.accessToken);const results=await Promise.all([f.submit(a.accessToken,q.addition),f.create(secret(),[{productId:2,quantity:1}])]);assert.equal(results.filter(r=>r.status<300).length,1);assert.equal(f.stock(2),0);f.close()});
for(const status of ['ready','completed','cancelled'])test(`pedido ${status} bloqueia acréscimo já cotado`,async()=>{const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken);await f.patch(a.order,{status});const r=await f.submit(a.accessToken,q.addition);assert.equal(r.status,409);assert.equal((await f.get(a.accessToken)).order.total,15);f.close()});
test('mudança de preço pede aceite e preserva preço original',async()=>{const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken);f.sqlite.exec('UPDATE products SET price=14 WHERE id=2');const changed=await f.submit(a.accessToken,q.addition);assert.equal(changed.code,'PRICE_CHANGED');assert.equal(changed.order.total,15);assert.equal(changed.addition.amount_cents,1400);const r=await f.submit(a.accessToken,changed.addition);assert.equal(r.order.total,29);assert.deepEqual(r.order.items.filter(i=>i.product_id===2).map(i=>i.unit_price),[13,14]);f.close()});
test('mudança de preço na aprovação exige novo aceite e nova aprovação',async()=>{const f=await fixture(),a=await f.create();await f.patch(a.order,{status:'preparing'});const q=await f.quote(a.accessToken),s=await f.submit(a.accessToken,q.addition);f.sqlite.exec('UPDATE products SET price=14 WHERE id=2');const change=await f.decide(s.order,s.addition);assert.equal(change.code,'PRICE_CHANGED');assert.equal(f.stock(2),29);assert.equal((await f.decide(s.order,change.addition)).code,'NOT_PENDING');const accepted=await f.submit(a.accessToken,change.addition);assert.equal(accepted.addition.state,'pending');const approved=await f.decide(accepted.order,accepted.addition);assert.equal(approved.order.total,29);f.close()});
test('acesso exige segredo, não revela hash e não permite agir no pedido alheio',async()=>{const f=await fixture(),a=await f.create(),b=await f.create(),q=await f.quote(a.accessToken);assert.equal((await f.get(a.code)).status,401);assert.equal((await f.get(secret())).status,404);assert.equal((await f.submit(b.accessToken,q.addition)).status,404);const r=await f.get(a.accessToken);assert.equal(r.order.access_hash,undefined);const list=await f.call(admin,'GET','/api/orders',null,{'x-admin-key':f.env.ADMIN_KEY});assert.ok(!JSON.stringify(list).includes('access_hash'));f.close()});
test('cancelamento reverte todos os itens efetivados uma única vez',async()=>{const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken),s=await f.submit(a.accessToken,q.addition);await Promise.all([f.patch(s.order,{status:'cancelled'}),f.patch(s.order,{status:'cancelled'})]);assert.equal(f.stock(1),30);assert.equal(f.stock(2),30);f.close()});

test('estoque alterado entre validação e gravação causa rollback de todos os itens',async()=>{
  const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken,[{productId:1,quantity:2},{productId:2,quantity:1}]);
  const batch=f.DB.batch;let changed=false;f.DB.batch=async statements=>{if(!changed&&statements.some(s=>s.sql.startsWith('INSERT INTO order_write_guards'))){changed=true;f.sqlite.exec('UPDATE products SET stock=0 WHERE id=2')}return batch(statements)};
  const r=await f.submit(a.accessToken,q.addition);assert.equal(r.status,409);assert.equal(f.stock(1),29);assert.equal((await f.get(a.accessToken)).order.total,15);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM order_write_guards').get().n,0);f.close();
});
test('migração de pedidos antigos preserva total pago e reexecução preserva pagamento parcial',async()=>{
  const f=testDB();f.sqlite.exec("CREATE TABLE orders(id INTEGER PRIMARY KEY,code TEXT NOT NULL,customer_name TEXT NOT NULL,customer_sector TEXT NOT NULL,customer_phone TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'new',total REAL NOT NULL,payment_status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO orders(id,code,customer_name,customer_sector,total,payment_status) VALUES(1,'ANTIGO-1','Cliente legado','Teste',15,'paid')");
  await setup(f.DB);assert.equal(f.sqlite.prepare('SELECT paid_amount_cents FROM orders').get().paid_amount_cents,1500);assert.equal(f.sqlite.prepare('SELECT amount_cents FROM order_payments').get().amount_cents,1500);
  f.sqlite.exec("UPDATE orders SET total=28,payment_status='pending'");await setup({...f.DB});assert.equal(f.sqlite.prepare('SELECT paid_amount_cents FROM orders').get().paid_amount_cents,1500);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM order_payments').get().n,1);f.close();
});
test('link de pedido antigo exige admin; rotação invalida acesso anterior',async()=>{
  const f=await fixture(),a=await f.create();const denied=await f.call(admin,'PATCH','/api/orders?id='+a.order.id,{action:'access'});assert.equal(denied.status,401);
  const fresh=await f.patch(a.order,{action:'access'});assert.equal(fresh.status,200);assert.equal((await f.get(a.accessToken)).status,404);assert.equal((await f.get(fresh.accessToken)).order.code,a.code);f.close();
});
test('quantidade negativa, decimal, excessiva ou inválida é recusada',async()=>{
  const f=await fixture(),a=await f.create();for(const quantity of [-1,0,1.5,51,'x'])assert.equal((await f.quote(a.accessToken,[{productId:2,quantity}])).status,400);assert.equal(f.stock(2),29);f.close();
});
test('chave de idempotência não pode ser reutilizada para itens diferentes',async()=>{
  const f=await fixture(),a=await f.create(),key=crypto.randomUUID();await f.quote(a.accessToken,undefined,key);const r=await f.quote(a.accessToken,[{productId:2,quantity:2}],key);assert.equal(r.code,'IDEMPOTENCY');assert.equal(f.stock(2),29);f.close();
});
test('mudança do pedido após a revisão exige nova conferência do cliente',async()=>{
  const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken);await f.patch(a.order,{paymentStatus:'paid'});
  const r=await f.call(customer,'POST','/api/customer-order?action=submit',{additionId:q.addition.id,expectedRevision:q.addition.revision,expectedOrderRevision:q.order.revision},{authorization:'Bearer '+a.accessToken});assert.equal(r.code,'STALE_ORDER');assert.equal(r.order.paid_amount_cents,1500);assert.equal(r.order.total,15);f.close();
});
test('excluir pedido devolve apenas itens efetivados, incluindo adicionais',async()=>{
  const f=await fixture(),a=await f.create(),q=await f.quote(a.accessToken);await f.submit(a.accessToken,q.addition);await f.patch(a.order,{status:'preparing'});const pending=await f.quote(a.accessToken);await f.submit(a.accessToken,pending.addition);
  const deleted=await f.call(admin,'DELETE','/api/orders?id='+a.order.id,null,{'x-admin-key':f.env.ADMIN_KEY});assert.equal(deleted.status,200);assert.equal(f.stock(1),30);assert.equal(f.stock(2),30);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM order_items').get().n,0);f.close();
});
test('fluxo de avisos recupera eventos pelo cursor e exige autenticação',async()=>{
  const f=await fixture(),a=await f.create();const baseline=await f.call(admin,'GET','/api/orders?updates=1',null,{'x-admin-key':f.env.ADMIN_KEY});const q=await f.quote(a.accessToken);await f.submit(a.accessToken,q.addition);
  assert.equal((await f.call(admin,'GET','/api/orders?updates=1&after=0')).status,401);
  const events=await f.call(admin,'GET','/api/orders?updates=1&after='+baseline.cursor,null,{'x-admin-key':f.env.ADMIN_KEY});assert.equal(events.events.length,1);assert.equal(events.events[0].kind,'addition_applied');assert.equal(events.events[0].items[0].quantity,1);assert.equal(events.events[0].code,a.code);f.close();
});
