const catalog=[
['Guaracamp 285 ml','Bebidas',2,'Guaracamp 285 ml','Bebidas'],['Coca-Cola 200 ml','Bebidas',3.5,'Coca-Cola 200 ml','Bebidas'],['Fanta Laranja 200 ml','Bebidas',3.5,'Fanta Laranja 200 ml','Bebidas'],['Fanta Guaraná 200 ml','Bebidas',3.5,'Fanta Guaraná 200 ml','Bebidas'],['Energético 300 ml','Bebidas',8,'Energético 300 ml','Bebidas'],['Suco de Manga 300 ml','Bebidas',6,'Suco de manga','Bebidas'],['Suco de Goiaba 300 ml','Bebidas',6,'Suco de goiaba','Bebidas'],
['Torta Salgada Pequena','Tortas salgadas',7,'Torta salgada pequena','Tortas'],['Torta Salgada Grande','Tortas salgadas',13,'Torta salgada grande','Tortas'],['Empadão de Frango','Tortas salgadas',7,'Empadão de frango','Empadões'],['Empadão de Camarão','Tortas salgadas',8,'Empadão de camarão','Empadões'],['Queijo com Presunto','Fritos',6,'Queijo com presunto','Fritos'],['Quibe','Fritos',6,'Quibe','Fritos'],['Risolho','Fritos',6,'Risolho','Fritos'],['Coxinha','Fritos',6,'Coxinha','Fritos'],
['Joelho Calabresa','Assados',7,'Calabresa','Assados'],['Joelho Queijo com Presunto','Assados',7,'Queijo com presunto','Assados'],['Joelho Frango','Assados',7,'Frango','Assados'],['Joelho Salsicha','Assados',7],['Croissant Queijo','Assados',7],['Croissant Queijo com Presunto','Assados',7],['Hambúrguer com Cheddar','Assados',7,'Hambúrguer com cheddar','Assados'],['Hambúrguer com Queijo e Presunto','Assados',7,'Hambúrguer com queijo e presunto','Assados'],['Pastel de Forno','Assados',7,'Pastel de forno','Assados'],
['Torta de Limão','Sobremesas',10],['Torta de Chocolate','Sobremesas',10],['Torta de Maracujá','Sobremesas',10],['Pavê de Paçoca','Sobremesas',10],['Pavê de Chocolate','Sobremesas',10],['Pavê de Limão','Sobremesas',10],['Bolo de Chocolate com Amendoim','Sobremesas',10],['Bolo de Prestígio','Sobremesas',10],['Bolo de Cenoura com Chocolate','Sobremesas',10],['Bolo de Chocolate com Limão','Sobremesas',10],['Bolo de Doce de Leite com Ameixa','Sobremesas',10]
];
const descriptions={
'Guaracamp 285 ml':'Bebida Guaracamp • 285 ml.','Coca-Cola 200 ml':'Refrigerante Coca-Cola • 200 ml.','Fanta Laranja 200 ml':'Refrigerante sabor laranja • 200 ml.','Fanta Guaraná 200 ml':'Refrigerante sabor guaraná • 200 ml.','Energético 300 ml':'Bebida energética • 300 ml.','Suco de Manga 300 ml':'Suco sabor manga • 300 ml.','Suco de Goiaba 300 ml':'Suco sabor goiaba • 300 ml.',
'Torta Salgada Pequena':'Torta salgada • tamanho pequeno.','Torta Salgada Grande':'Torta salgada • tamanho grande.','Empadão de Frango':'Empadão salgado com recheio de frango.','Empadão de Camarão':'Empadão salgado com recheio de camarão.','Queijo com Presunto':'Salgado frito de queijo com presunto.','Quibe':'Salgado frito • quibe.','Risolho':'Salgado frito • risolho.','Coxinha':'Salgado frito • coxinha.',
'Joelho Calabresa':'Salgado assado • sabor calabresa.','Joelho Queijo com Presunto':'Salgado assado de queijo com presunto.','Joelho Frango':'Salgado assado • sabor frango.','Joelho Salsicha':'Salgado assado • sabor salsicha.','Croissant Queijo':'Croissant assado • sabor queijo.','Croissant Queijo com Presunto':'Croissant assado de queijo com presunto.','Hambúrguer com Cheddar':'Salgado assado de hambúrguer com cheddar.','Hambúrguer com Queijo e Presunto':'Salgado assado de hambúrguer, queijo e presunto.','Pastel de Forno':'Pastel assado no forno.',
'Torta de Limão':'Sobremesa sabor limão.','Torta de Chocolate':'Sobremesa sabor chocolate.','Torta de Maracujá':'Sobremesa sabor maracujá.','Pavê de Paçoca':'Sobremesa • pavê sabor paçoca.','Pavê de Chocolate':'Sobremesa • pavê sabor chocolate.','Pavê de Limão':'Sobremesa • pavê sabor limão.','Bolo de Chocolate com Amendoim':'Bolo de chocolate com amendoim.','Bolo de Prestígio':'Bolo sabor prestígio.','Bolo de Cenoura com Chocolate':'Bolo de cenoura com chocolate.','Bolo de Chocolate com Limão':'Bolo de chocolate com limão.','Bolo de Doce de Leite com Ameixa':'Bolo de doce de leite com ameixa.'
};
const defaultFeatured=['Torta Salgada Pequena','Torta Salgada Grande','Empadão de Frango','Joelho Queijo com Presunto','Queijo com Presunto','Torta de Limão'];
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});const auth=(r,e)=>e.ADMIN_KEY&&r.headers.get('x-admin-key')===e.ADMIN_KEY;
async function ensureColumn(db,name,definition){const {results}=await db.prepare('PRAGMA table_info(products)').all();if(results.some(c=>c.name===name))return;try{await db.prepare(`ALTER TABLE products ADD COLUMN ${name} ${definition}`).run()}catch(error){if(!String(error).toLowerCase().includes('duplicate column'))throw error}}
async function setupProducts(db){await db.prepare('CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,price REAL NOT NULL,available INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();await ensureColumn(db,'stock','INTEGER DEFAULT NULL');await ensureColumn(db,'low_stock_threshold','INTEGER NOT NULL DEFAULT 5');await ensureColumn(db,'description',"TEXT NOT NULL DEFAULT ''");await ensureColumn(db,'featured','INTEGER NOT NULL DEFAULT 0');await ensureColumn(db,'featured_order','INTEGER NOT NULL DEFAULT 0')}
async function syncCatalog(db){await setupProducts(db);await db.prepare('CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)').run();const version=await db.prepare("SELECT value FROM app_meta WHERE key='catalog_version'").first();if(version?.value==='3')return;const find=db.prepare('SELECT id,description,featured FROM products WHERE lower(name)=lower(?) AND category=? LIMIT 1'),update=db.prepare("UPDATE products SET name=?,category=?,price=?,sort_order=?,description=CASE WHEN trim(description)='' THEN ? ELSE description END WHERE id=?"),insert=db.prepare('INSERT INTO products(name,category,price,available,sort_order,description,featured,featured_order) VALUES(?,?,?,?,?,?,?,?)');for(let i=0;i<catalog.length;i++){const [name,category,price,oldName=name,oldCategory=category]=catalog[i];let row=await find.bind(name,category).first();if(!row&&oldName)row=await find.bind(oldName,oldCategory).first();const featuredIndex=defaultFeatured.indexOf(name),featured=featuredIndex>=0?1:0;if(row){await update.bind(name,category,price,i+1,descriptions[name]||'',row.id).run();if(version?.value!=='3'&&featured)await db.prepare('UPDATE products SET featured=1,featured_order=? WHERE id=? AND featured=0').bind(featuredIndex+1,row.id).run()}else await insert.bind(name,category,price,1,i+1,descriptions[name]||'',featured,featuredIndex+1).run()}await db.prepare("INSERT OR REPLACE INTO app_meta(key,value) VALUES('catalog_version','3')").run()}
export async function onRequestGet({request,env}){try{await syncCatalog(env.DB);const admin=new URL(request.url).searchParams.has('admin');if(admin&&!auth(request,env))return json({error:'Não autorizado'},401);const fields=admin?'id,name,category,price,available,stock,low_stock_threshold,description,featured,featured_order':'id,name,category,price,CASE WHEN available=1 AND (stock IS NULL OR stock>0) THEN 1 ELSE 0 END available,stock,low_stock_threshold,description,featured,featured_order';const {results}=await env.DB.prepare(`SELECT ${fields} FROM products ORDER BY sort_order,id`).all();return json(results)}catch(error){return json({error:'Banco não configurado',detail:String(error)},503)}}
export async function onRequestPatch({request,env}){if(!auth(request,env))return json({error:'Não autorizado'},401);try{await setupProducts(env.DB);const body=await request.json(),id=Number(new URL(request.url).searchParams.get('id'));if(!Number.isInteger(id)||id<1)return json({error:'Produto inválido.'},400);const current=await env.DB.prepare('SELECT id,available,stock,low_stock_threshold,description,featured,featured_order FROM products WHERE id=?').bind(id).first();if(!current)return json({error:'Produto não encontrado.'},404);const available=typeof body.available==='boolean'?(body.available?1:0):Number(current.available);let stock=current.stock;if(Object.prototype.hasOwnProperty.call(body,'stock')){stock=body.stock===null||body.stock===''?null:Number(body.stock);if(stock!==null&&(!Number.isInteger(stock)||stock<0||stock>99999))return json({error:'Estoque inválido.'},400)}let threshold=Object.prototype.hasOwnProperty.call(body,'lowStockThreshold')?Number(body.lowStockThreshold):Number(current.low_stock_threshold||5);if(!Number.isInteger(threshold)||threshold<0||threshold>9999)return json({error:'Limite de estoque inválido.'},400);const description=Object.prototype.hasOwnProperty.call(body,'description')?String(body.description||'').trim():current.description;if(description.length>160)return json({error:'A descrição deve ter no máximo 160 caracteres.'},400);const featured=typeof body.featured==='boolean'?(body.featured?1:0):Number(current.featured||0);let featuredOrder=Object.prototype.hasOwnProperty.call(body,'featuredOrder')?Number(body.featuredOrder):Number(current.featured_order||0);if(!Number.isInteger(featuredOrder)||featuredOrder<0||featuredOrder>99)return json({error:'Ordem de destaque inválida.'},400);if(featured){const count=await env.DB.prepare('SELECT COUNT(*) total FROM products WHERE featured=1 AND id<>?').bind(id).first();if(Number(count.total)>=6&&!Number(current.featured))return json({error:'Você pode selecionar no máximo 6 destaques.'},400);if(featuredOrder===0)featuredOrder=Number(count.total)+1}else featuredOrder=0;await env.DB.prepare('UPDATE products SET available=?,stock=?,low_stock_threshold=?,description=?,featured=?,featured_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(available,stock,threshold,description,featured,featuredOrder,id).run();return json({ok:true,product:{id,available,stock,low_stock_threshold:threshold,description,featured,featured_order:featuredOrder}})}catch(error){return json({error:'Não foi possível atualizar o produto.',detail:String(error)},500)}}
