const catalog=[
['Guaracamp 285 ml','Bebidas',2,'Guaracamp 285 ml','Bebidas'],['Coca-Cola 200 ml','Bebidas',3.5,'Coca-Cola 200 ml','Bebidas'],['Fanta Laranja 200 ml','Bebidas',3.5,'Fanta Laranja 200 ml','Bebidas'],['Fanta Guaraná 200 ml','Bebidas',3.5,'Fanta Guaraná 200 ml','Bebidas'],['Energético 300 ml','Bebidas',8,'Energético 300 ml','Bebidas'],['Suco de Manga 300 ml','Bebidas',6,'Suco de manga','Bebidas'],['Suco de Goiaba 300 ml','Bebidas',6,'Suco de goiaba','Bebidas'],
['Torta Salgada Pequena','Tortas salgadas',7,'Torta salgada pequena','Tortas'],['Torta Salgada Grande','Tortas salgadas',13,'Torta salgada grande','Tortas'],['Empadão de Frango','Tortas salgadas',7,'Empadão de frango','Empadões'],['Empadão de Camarão','Tortas salgadas',8,'Empadão de camarão','Empadões'],['Queijo com Presunto','Fritos',6,'Queijo com presunto','Fritos'],['Quibe','Fritos',6,'Quibe','Fritos'],['Risolho','Fritos',6,'Risolho','Fritos'],['Coxinha','Fritos',6,'Coxinha','Fritos'],
['Joelho Calabresa','Assados',7,'Calabresa','Assados'],['Joelho Queijo com Presunto','Assados',7,'Queijo com presunto','Assados'],['Joelho Frango','Assados',7,'Frango','Assados'],['Joelho Salsicha','Assados',7],['Croissant Queijo','Assados',7],['Croissant Queijo com Presunto','Assados',7],['Hambúrguer com Cheddar','Assados',7,'Hambúrguer com cheddar','Assados'],['Hambúrguer com Queijo e Presunto','Assados',7,'Hambúrguer com queijo e presunto','Assados'],['Pastel de Forno','Assados',7,'Pastel de forno','Assados'],
['Torta de Limão','Sobremesas',10],['Torta de Chocolate','Sobremesas',10],['Torta de Maracujá','Sobremesas',10],['Pavê de Paçoca','Sobremesas',10],['Pavê de Chocolate','Sobremesas',10],['Pavê de Limão','Sobremesas',10],['Bolo de Chocolate com Amendoim','Sobremesas',10],['Bolo de Prestígio','Sobremesas',10],['Bolo de Cenoura com Chocolate','Sobremesas',10],['Bolo de Chocolate com Limão','Sobremesas',10],['Bolo de Doce de Leite com Ameixa','Sobremesas',10]
];
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});const auth=(r,e)=>e.ADMIN_KEY&&r.headers.get('x-admin-key')===e.ADMIN_KEY;
async function syncCatalog(db){await db.prepare('CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)').run();const version=await db.prepare("SELECT value FROM app_meta WHERE key='catalog_version'").first();if(version?.value==='2')return;const find=db.prepare('SELECT id FROM products WHERE lower(name)=lower(?) AND category=? LIMIT 1'),update=db.prepare('UPDATE products SET name=?,category=?,price=?,sort_order=? WHERE id=?'),insert=db.prepare('INSERT INTO products(name,category,price,available,sort_order) VALUES(?,?,?,?,?)');for(let i=0;i<catalog.length;i++){const [name,category,price,oldName=name,oldCategory=category]=catalog[i];let row=await find.bind(name,category).first();if(!row&&oldName)row=await find.bind(oldName,oldCategory).first();if(row)await update.bind(name,category,price,i+1,row.id).run();else await insert.bind(name,category,price,1,i+1).run()}await db.prepare("INSERT OR REPLACE INTO app_meta(key,value) VALUES('catalog_version','2')").run()}
export async function onRequestGet({request,env}){try{await syncCatalog(env.DB);if(new URL(request.url).searchParams.has('admin')&&!auth(request,env))return json({error:'Não autorizado'},401);const {results}=await env.DB.prepare('SELECT id,name,category,price,available FROM products ORDER BY sort_order,id').all();return json(results)}catch{return json({error:'Banco não configurado'},503)}}export async function onRequestPatch({request,env}){if(!auth(request,env))return json({error:'Não autorizado'},401);const body=await request.json(),id=new URL(request.url).searchParams.get('id');if(typeof body.available!=='boolean'||!id)return json({error:'Inválido'},400);await env.DB.prepare('UPDATE products SET available=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(body.available?1:0,id).run();return json({ok:true})}
