document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/orders.css">');
const $=s=>document.querySelector(s),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let key=sessionStorage.getItem('lg-key')||'',orders=[],historyOrders=[],refreshTimer;
const statusLabels={new:'Novo',preparing:'Em preparo',ready:'Pronto',completed:'Finalizado',cancelled:'Cancelado'};
async function api(url,options={}){return fetch(url,{...options,headers:{'content-type':'application/json','x-admin-key':key,...options.headers}})}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateTime(value){return new Date(value.replace(' ','T')+'Z').toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function enter(){
  $('#login-status').textContent='Verificando…';
  const [productsResponse,ordersResponse]=await Promise.all([api('/api/products?admin=1'),api('/api/orders')]);
  if(!productsResponse.ok||!ordersResponse.ok)return $('#login-status').textContent='Chave incorreta ou sistema ainda não configurado.';
  sessionStorage.setItem('lg-key',key);$('#login').hidden=true;$('#admin-area').hidden=false;
  renderProducts(await productsResponse.json());orders=await ordersResponse.json();renderOrders();startRefresh();
}
function renderProducts(rows){$('#admin-list').innerHTML=rows.map(p=>`<div class="admin-row"><div><strong>${escapeHtml(p.name)}</strong><p>${escapeHtml(p.category)} • ${money(p.price)}</p></div><button class="switch ${p.available?'on':''}" data-product-id="${p.id}" data-on="${p.available?1:0}" aria-label="Alterar disponibilidade"></button></div>`).join('')}
function orderCard(o){const digits=o.customer_phone.replace(/\D/g,''),whatsapp=digits?(digits.startsWith('55')?digits:'55'+digits):'',phone=whatsapp?`<a class="order-contact" href="https://wa.me/${whatsapp}" target="_blank" rel="noopener">Falar com cliente</a>`:'';return `<article class="order-card status-${o.status}"><header><div><span class="order-code">${escapeHtml(o.code)}</span><h3>${escapeHtml(o.customer_name)}</h3><p>${escapeHtml(o.customer_sector)} • ${dateTime(o.created_at)}</p></div><span class="order-badge">${statusLabels[o.status]||o.status}</span></header><ul>${o.items.map(i=>`<li><span>${i.quantity}× ${escapeHtml(i.product_name)}</span><strong>${money(i.subtotal)}</strong></li>`).join('')}</ul>${o.note?`<p class="order-note"><strong>Observação:</strong> ${escapeHtml(o.note)}</p>`:''}<div class="order-total"><span>Total</span><strong>${money(o.total)}</strong></div><footer><select data-order-id="${o.id}" aria-label="Alterar status"><option value="new" ${o.status==='new'?'selected':''}>Novo</option><option value="preparing" ${o.status==='preparing'?'selected':''}>Em preparo</option><option value="ready" ${o.status==='ready'?'selected':''}>Pronto</option><option value="completed" ${o.status==='completed'?'selected':''}>Finalizado</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelado</option></select>${phone}</footer></article>`}
function renderOrders(){const filter=$('#status-filter').value,visible=filter==='all'?orders:orders.filter(o=>o.status===filter);$('#new-count').textContent=orders.filter(o=>o.status==='new').length;$('#orders-list').innerHTML=visible.length?visible.map(orderCard).join(''):'<p class="orders-empty">Nenhum pedido encontrado.</p>'}
function renderHistory(data){historyOrders=data.orders||[];const summary=data.summary||{};$('#history-count').textContent=summary.count||0;$('#history-revenue').textContent=money(summary.revenue||0);$('#history-average').textContent=money(summary.average||0);$('#history-list').innerHTML=historyOrders.length?historyOrders.map(orderCard).join(''):'<p class="orders-empty">Nenhum pedido encontrado nesse período.</p>';$('#history-message').textContent=historyOrders.length===500?'Mostrando os 500 pedidos mais recentes da pesquisa.':''}
async function loadHistory(){const params=new URLSearchParams({history:'1'}),from=$('#history-from').value,to=$('#history-to').value,q=$('#history-query').value.trim(),status=$('#history-status').value;if(from)params.set('from',from);if(to)params.set('to',to);if(q)params.set('q',q);if(status!=='all')params.set('status',status);$('#history-message').textContent='Pesquisando…';const r=await api('/api/orders?'+params);if(!r.ok)return $('#history-message').textContent='Não foi possível carregar o histórico.';renderHistory(await r.json())}
async function loadOrders(silent=false){if(!silent)$('#orders-status').textContent='Atualizando…';const r=await api('/api/orders');if(!r.ok)return $('#orders-status').textContent='Não foi possível atualizar os pedidos.';orders=await r.json();renderOrders();$('#orders-status').textContent=`Atualizado às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}
function startRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>loadOrders(true),20000)}
$('#login-form').onsubmit=e=>{e.preventDefault();key=$('#key').value;enter()};
$('#admin-list').onclick=async e=>{const b=e.target.closest('[data-product-id]');if(!b)return;const available=b.dataset.on!=='1';$('#save-status').textContent='Salvando…';b.disabled=true;const r=await api('/api/products?id='+b.dataset.productId,{method:'PATCH',body:JSON.stringify({available})});b.disabled=false;if(!r.ok)return $('#save-status').textContent='Não foi possível salvar.';b.dataset.on=available?'1':'0';b.classList.toggle('on',available);$('#save-status').textContent=available?'Produto disponível no site.':'Produto marcado como esgotado.'};
$('.admin-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#orders').hidden=b.dataset.tab!=='orders';$('#history').hidden=b.dataset.tab!=='history';$('#products').hidden=b.dataset.tab!=='products';if(b.dataset.tab==='history'&&!historyOrders.length)loadHistory()};
$('#status-filter').onchange=renderOrders;
async function changeOrderStatus(select){select.disabled=true;const r=await api('/api/orders?id='+select.dataset.orderId,{method:'PATCH',body:JSON.stringify({status:select.value})});select.disabled=false;if(!r.ok)return alert('Não foi possível atualizar o pedido.');const current=orders.find(o=>+o.id===+select.dataset.orderId),historic=historyOrders.find(o=>+o.id===+select.dataset.orderId);if(current)current.status=select.value;if(historic)historic.status=select.value;renderOrders();if(!$('#history').hidden)loadHistory()}
$('#orders-list').onchange=e=>{const select=e.target.closest('[data-order-id]');if(select)changeOrderStatus(select)};
$('#history-list').onchange=e=>{const select=e.target.closest('[data-order-id]');if(select)changeOrderStatus(select)};
$('#history-form').onsubmit=e=>{e.preventDefault();loadHistory()};
$('#history-clear').onclick=()=>{$('#history-form').reset();loadHistory()};
if(key)enter();
