document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/orders.css?v=23">');
const $=selector=>document.querySelector(selector),money=value=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let key=sessionStorage.getItem('lg-key')||'',orders=[],historyOrders=[],financeOrders=[],products=[],refreshTimer,ordersInitialized=false,knownOrderIds=new Set(),audioContext;
const statusLabels={new:'Novo',preparing:'Confirmado',ready:'Pronto',completed:'Finalizado',cancelled:'Cancelado'},paymentLabels={pending:'Pendente',paid:'Pago'},methodLabels={later:'Fiado/prazo',pix:'Pix',cash:'Dinheiro',card:'Cartão'};
async function api(url,options={}){return fetch(url,{...options,headers:{'content-type':'application/json','x-admin-key':key,...options.headers}})}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function dateTime(value){return new Date(value.replace(' ','T')+(value.includes('T')?'':'Z')).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
async function responseData(response){try{return await response.json()}catch{return {}}}

async function enter(){
  $('#login-status').textContent='Verificando…';
  const [productsResponse,ordersResponse]=await Promise.all([api('/api/products?admin=1'),api('/api/orders')]);
  if(!productsResponse.ok||!ordersResponse.ok)return $('#login-status').textContent='Chave incorreta ou sistema ainda não configurado.';
  sessionStorage.setItem('lg-key',key);$('#login').hidden=true;$('#admin-area').hidden=false;
  products=await productsResponse.json();orders=await ordersResponse.json();knownOrderIds=new Set(orders.map(order=>Number(order.id)));ordersInitialized=true;renderProducts();renderOrders();startRefresh();
}

function renderProducts(){
  const low=products.filter(product=>product.stock!==null&&Number(product.stock)>0&&Number(product.stock)<=Number(product.low_stock_threshold||5)).length,out=products.filter(product=>product.stock!==null&&Number(product.stock)===0).length,tracked=products.filter(product=>product.stock!==null).length,featured=products.filter(product=>Number(product.featured)).length;
  $('#stock-summary').innerHTML=`<article><span>Produtos controlados</span><strong>${tracked}</strong></article><article><span>Estoque baixo</span><strong>${low}</strong></article><article><span>Esgotados</span><strong>${out}</strong></article><article><span>Destaques</span><strong>${featured}/6</strong></article>`;
  $('#admin-list').innerHTML=products.map(product=>{const stockClass=product.stock===null?'untracked':Number(product.stock)===0?'out':Number(product.stock)<=Number(product.low_stock_threshold||5)?'low':'ok',stockText=product.stock===null?'Não controlado':Number(product.stock)===0?'Esgotado':`${product.stock} unidade(s)`;return `<div class="admin-row product-admin-row ${stockClass}" data-product-row="${product.id}"><div class="product-admin-head"><div class="stock-product"><strong>${escapeHtml(product.name)}</strong><p>${escapeHtml(product.category)} • ${money(product.price)}</p><span class="stock-state">${stockText}</span></div><label class="availability-control"><span>Disponível</span><button type="button" class="switch ${product.available?'on':''}" data-availability data-on="${product.available?1:0}" aria-label="Alterar disponibilidade"></button></label></div><label class="description-field">Descrição do produto<textarea data-description maxlength="160" rows="2" placeholder="Descrição curta, com até duas linhas">${escapeHtml(product.description||'')}</textarea><small><span data-char-count>${String(product.description||'').length}</span>/160 caracteres</small></label><div class="product-admin-controls"><label>Saldo<input class="stock-input" data-stock type="number" min="0" max="99999" value="${product.stock===null?'':product.stock}" placeholder="Sem controle"></label><label>Alerta abaixo de<input class="stock-input" data-threshold type="number" min="0" max="9999" value="${product.low_stock_threshold??5}"></label><label class="featured-control"><input data-featured type="checkbox" ${product.featured?'checked':''}> <span>Exibir como destaque</span></label><label>Ordem do destaque<input class="stock-input" data-featured-order type="number" min="1" max="6" value="${product.featured?product.featured_order||'':''}" ${product.featured?'':'disabled'} placeholder="1 a 6"></label><button class="secondary save-stock" data-save-stock>Salvar produto</button></div></div>`}).join('');
}

function orderCard(order){
  const digits=String(order.customer_phone||'').replace(/\D/g,''),whatsapp=digits?(digits.startsWith('55')?digits:'55'+digits):'',phone=whatsapp?`<a class="order-contact" href="https://wa.me/${whatsapp}" target="_blank" rel="noopener">Falar com cliente</a>`:'',confirm=order.status==='new'?`<button class="confirm-order" data-confirm-id="${order.id}">✓ Confirmar pedido</button>`:'';
  return `<article class="order-card status-${order.status} payment-${order.payment_status||'pending'}"><header><div><span class="order-code">${escapeHtml(order.code)}</span><h3>${escapeHtml(order.customer_name)}</h3><p>${escapeHtml(order.customer_sector)} • ${dateTime(order.created_at)}</p></div><div class="card-badges"><span class="order-badge">${statusLabels[order.status]||order.status}</span><span class="payment-badge">${paymentLabels[order.payment_status]||'Pendente'}</span></div></header><ul>${order.items.map(item=>`<li><span>${item.quantity}× ${escapeHtml(item.product_name)}</span><strong>${money(item.subtotal)}</strong></li>`).join('')}</ul>${order.note?`<p class="order-note"><strong>Observação:</strong> ${escapeHtml(order.note)}</p>`:''}<div class="payment-info"><span>Pagamento: <strong>${methodLabels[order.payment_method]||'Fiado/prazo'}</strong></span>${order.paid_at?`<small>Pago em ${dateTime(order.paid_at)}</small>`:''}</div><div class="order-total"><span>Total</span><strong>${money(order.total)}</strong></div><footer><div class="order-controls"><select data-order-id="${order.id}" aria-label="Alterar status do pedido"><option value="new" ${order.status==='new'?'selected':''}>Novo</option><option value="preparing" ${order.status==='preparing'?'selected':''}>Confirmado</option><option value="ready" ${order.status==='ready'?'selected':''}>Pronto</option><option value="completed" ${order.status==='completed'?'selected':''}>Finalizado</option><option value="cancelled" ${order.status==='cancelled'?'selected':''}>Cancelado</option></select><select data-payment-id="${order.id}" aria-label="Alterar pagamento"><option value="pending" ${order.payment_status!=='paid'?'selected':''}>Pagamento pendente</option><option value="paid" ${order.payment_status==='paid'?'selected':''}>Pagamento recebido</option></select>${confirm}<button class="delete-order" data-delete-id="${order.id}" data-delete-code="${escapeHtml(order.code)}" title="Excluir pedido">Excluir</button></div>${phone}</footer></article>`;
}

function renderOrders(){const filter=$('#status-filter').value,visible=filter==='all'?orders:orders.filter(order=>order.status===filter),active=orders.filter(order=>!['completed','cancelled'].includes(order.status));$('#new-count').textContent=orders.filter(order=>order.status==='new').length;$('#summary-new').textContent=orders.filter(order=>order.status==='new').length;$('#summary-confirmed').textContent=orders.filter(order=>order.status==='preparing').length;$('#summary-ready').textContent=orders.filter(order=>order.status==='ready').length;$('#summary-total').textContent=money(active.reduce((sum,order)=>sum+Number(order.total),0));$('#orders-list').innerHTML=visible.length?visible.map(orderCard).join(''):'<p class="orders-empty">Nenhum pedido encontrado.</p>'}
function renderHistory(data){historyOrders=data.orders||[];const summary=data.summary||{};$('#history-count').textContent=summary.count||0;$('#history-revenue').textContent=money(summary.revenue||0);$('#history-average').textContent=money(summary.average||0);$('#history-list').innerHTML=historyOrders.length?historyOrders.map(orderCard).join(''):'<p class="orders-empty">Nenhum pedido encontrado nesse período.</p>';$('#history-message').textContent=historyOrders.length===500?'Mostrando os 500 pedidos mais recentes da pesquisa.':''}
function renderFinance(data){financeOrders=data.orders||[];const summary=data.summary||{};$('#finance-total').textContent=money(summary.revenue||0);$('#finance-paid').textContent=money(summary.paid||0);$('#finance-pending').textContent=money(summary.pending||0);$('#finance-customers').textContent=summary.customers||0;$('#finance-list').innerHTML=financeOrders.length?financeOrders.map(orderCard).join(''):'<p class="orders-empty">Nenhuma venda encontrada nesse filtro.</p>';$('#finance-message').textContent=financeOrders.length===500?'Mostrando as 500 vendas mais recentes.':''}

async function loadHistory(){const params=new URLSearchParams({history:'1'}),from=$('#history-from').value,to=$('#history-to').value,q=$('#history-query').value.trim(),status=$('#history-status').value;if(from)params.set('from',from);if(to)params.set('to',to);if(q)params.set('q',q);if(status!=='all')params.set('status',status);$('#history-message').textContent='Pesquisando…';const response=await api('/api/orders?'+params);if(!response.ok)return $('#history-message').textContent='Não foi possível carregar o histórico.';renderHistory(await response.json())}
async function loadFinance(){const params=new URLSearchParams({finance:'1'}),from=$('#finance-from').value,to=$('#finance-to').value,q=$('#finance-query').value.trim(),payment=$('#finance-payment').value;if(from)params.set('from',from);if(to)params.set('to',to);if(q)params.set('q',q);if(payment!=='all')params.set('payment',payment);$('#finance-message').textContent='Calculando…';const response=await api('/api/orders?'+params);if(!response.ok)return $('#finance-message').textContent='Não foi possível carregar o financeiro.';renderFinance(await response.json())}
async function loadProducts(){const response=await api('/api/products?admin=1');if(response.ok){products=await response.json();renderProducts()}}

function playAlert(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=880;gain.gain.setValueAtTime(.18,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.45);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.45)}catch{}}
function alertNewOrders(incoming){if(!incoming.length)return;playAlert();const total=incoming.reduce((sum,order)=>sum+Number(order.total),0),message=incoming.length===1?`${incoming[0].customer_name} • ${money(incoming[0].total)}`:`${incoming.length} novos pedidos • ${money(total)}`;if('Notification'in window&&Notification.permission==='granted')new Notification('Novo pedido — L&G Delícias',{body:message,icon:'/assets/logo.jpg',tag:'lg-new-order'});document.title=`(${incoming.length}) Novo pedido | L&G Delícias`;setTimeout(()=>document.title='Central de Pedidos | L&G Delícias',10000)}
async function loadOrders(silent=false){if(!silent)$('#orders-status').textContent='Atualizando…';const response=await api('/api/orders');if(!response.ok)return $('#orders-status').textContent='Não foi possível atualizar os pedidos.';const fresh=await response.json(),incoming=ordersInitialized?fresh.filter(order=>order.status==='new'&&!knownOrderIds.has(Number(order.id))):[];orders=fresh;for(const order of orders)knownOrderIds.add(Number(order.id));ordersInitialized=true;renderOrders();if(incoming.length)alertNewOrders(incoming);$('#orders-status').textContent=`Atualizado às ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}
function startRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>loadOrders(true),8000)}

async function updateOrder(id,payload,select){if(select)select.disabled=true;const response=await api('/api/orders?id='+id,{method:'PATCH',body:JSON.stringify(payload)});if(select)select.disabled=false;const data=await responseData(response);if(!response.ok){alert(data.error||'Não foi possível atualizar o pedido.');await loadOrders(true);return}if(data.notification?.mode==='manual'){window.open(`https://wa.me/${data.notification.phone}?text=${encodeURIComponent(data.notification.message)}`,'_blank','noopener')}else if(data.notification?.mode==='automatic'&&data.notification.sent){alert('Pedido confirmado e cliente avisado automaticamente pelo WhatsApp.')}await Promise.all([loadOrders(true),loadProducts()]);if(!$('#history').hidden)loadHistory();if(!$('#finance').hidden)loadFinance()}
async function confirmOrder(id){await updateOrder(id,{status:'preparing'})}
async function deleteOrder(button){const code=button.dataset.deleteCode,typed=prompt(`Para excluir definitivamente o pedido ${code}, digite o código abaixo:\n\n${code}`);if(typed===null)return;if(typed.trim().toUpperCase()!==code.toUpperCase())return alert('Código diferente. O pedido não foi excluído.');button.disabled=true;button.textContent='Excluindo…';const response=await api('/api/orders?id='+button.dataset.deleteId,{method:'DELETE'}),data=await responseData(response);if(!response.ok){button.disabled=false;button.textContent='Excluir';return alert(data.error||'Não foi possível excluir o pedido.')}await Promise.all([loadOrders(true),loadProducts()]);if(!$('#history').hidden)loadHistory();if(!$('#finance').hidden)loadFinance()}

async function saveProduct(row,toggleOnly=false){const id=row.dataset.productRow,stockInput=row.querySelector('[data-stock]'),thresholdInput=row.querySelector('[data-threshold]'),descriptionInput=row.querySelector('[data-description]'),featuredInput=row.querySelector('[data-featured]'),featuredOrderInput=row.querySelector('[data-featured-order]'),availability=row.querySelector('[data-availability]'),button=row.querySelector('[data-save-stock]'),body={available:availability.dataset.on==='1',stock:stockInput.value===''?null:Number(stockInput.value),lowStockThreshold:Number(thresholdInput.value||0),description:descriptionInput.value.trim(),featured:featuredInput.checked,featuredOrder:featuredInput.checked?Number(featuredOrderInput.value||0):0};if(toggleOnly){body.available=!body.available;availability.disabled=true}else{button.disabled=true;button.textContent='Salvando…'}$('#save-status').textContent='Salvando produto…';const response=await api('/api/products?id='+id,{method:'PATCH',body:JSON.stringify(body)}),data=await responseData(response);if(!response.ok){alert(data.error||'Não foi possível salvar.');await loadProducts();return}$('#save-status').textContent='Produto atualizado. O cardápio já recebeu a alteração.';await loadProducts()}

$('#login-form').onsubmit=event=>{event.preventDefault();key=$('#key').value;enter()};
$('.admin-tabs').onclick=event=>{const button=event.target.closest('[data-tab]');if(!button)return;document.querySelectorAll('.admin-tabs button').forEach(item=>item.classList.toggle('active',item===button));['orders','finance','history','products'].forEach(tab=>$('#'+tab).hidden=button.dataset.tab!==tab);if(button.dataset.tab==='history'&&!historyOrders.length)loadHistory();if(button.dataset.tab==='finance')loadFinance();if(button.dataset.tab==='products')loadProducts()};
$('#admin-list').onclick=event=>{const row=event.target.closest('[data-product-row]');if(!row)return;if(event.target.closest('[data-availability]'))saveProduct(row,true);if(event.target.closest('[data-save-stock]'))saveProduct(row)};
$('#admin-list').oninput=event=>{const row=event.target.closest('[data-product-row]');if(!row)return;if(event.target.matches('[data-description]'))row.querySelector('[data-char-count]').textContent=event.target.value.length;if(event.target.matches('[data-featured]')){const order=row.querySelector('[data-featured-order]');order.disabled=!event.target.checked;if(event.target.checked&&!order.value)order.value=products.filter(product=>Number(product.featured)).length+1}};
$('#status-filter').onchange=renderOrders;
for(const id of ['orders-list','history-list','finance-list']){$('#'+id).onchange=event=>{const orderSelect=event.target.closest('[data-order-id]'),paymentSelect=event.target.closest('[data-payment-id]');if(orderSelect)updateOrder(orderSelect.dataset.orderId,{status:orderSelect.value},orderSelect);if(paymentSelect)updateOrder(paymentSelect.dataset.paymentId,{paymentStatus:paymentSelect.value},paymentSelect)};$('#'+id).onclick=event=>{const confirm=event.target.closest('[data-confirm-id]'),remove=event.target.closest('[data-delete-id]');if(confirm)confirmOrder(confirm.dataset.confirmId);if(remove)deleteOrder(remove)}}
$('#enable-alerts').onclick=async()=>{playAlert();if(!('Notification'in window))return alert('Este navegador não oferece notificações. O alerta sonoro continuará funcionando.');const permission=await Notification.requestPermission();$('#enable-alerts').textContent=permission==='granted'?'🔔 Alertas ativos':'🔕 Alertas bloqueados'};
$('#refresh-orders').onclick=()=>loadOrders();
$('#history-form').onsubmit=event=>{event.preventDefault();loadHistory()};$('#history-clear').onclick=()=>{$('#history-form').reset();loadHistory()};
$('#finance-form').onsubmit=event=>{event.preventDefault();loadFinance()};$('#finance-clear').onclick=()=>{$('#finance-form').reset();loadFinance()};
if(key)enter();
